import { AppData } from './domain';
export const FOOD_IMAGE = '/food.jpg';
export function demoData(): AppData {
  return {
    profile: { id: 'customer-demo', role: 'customer', name: 'Alex', phone: '9876543210' },
    restaurants: [
      {
        id: 'r1',
        owner_id: 'restaurant-demo',
        name: 'The Everyday Kitchen',
        slug: 'the-everyday-kitchen',
        description:
          'Comfort food, cooked with care. Freshly made Indian favourites from our neighbourhood kitchen.',
        cuisine: 'South Indian',
        address: '12, Church Street, Bengaluru',
        image: FOOD_IMAGE,
        open: true,
        approved: true,
        hours: '10:00–22:00',
        lat: 12.975,
        lng: 77.601,
        eta: 25,
        rating: null,
      },
      {
        id: 'r2',
        owner_id: 'owner-2',
        name: 'Biryani & Beyond',
        slug: 'biryani-and-beyond',
        description:
          'Slow-cooked rice, fragrant spices, and generous portions. A little celebration in every order.',
        cuisine: 'Biryani',
        address: 'Indiranagar, Bengaluru',
        image: FOOD_IMAGE,
        open: true,
        approved: true,
        hours: '11:00–23:00',
        lat: 12.978,
        lng: 77.638,
        eta: 35,
        rating: null,
      },
      {
        id: 'r3',
        owner_id: 'owner-3',
        name: 'Green Bowl Co.',
        slug: 'green-bowl-co',
        description: 'Colourful bowls and seasonal ingredients, made fresh for your everyday.',
        cuisine: 'Healthy',
        address: 'Lavelle Road, Bengaluru',
        image: FOOD_IMAGE,
        open: true,
        approved: true,
        hours: '09:00–21:00',
        lat: 12.967,
        lng: 77.599,
        eta: 20,
        rating: null,
      },
    ],
    menu: [
      {
        id: 'm1',
        restaurant_id: 'r1',
        name: 'Homestyle veg thali',
        description: 'Dal, seasonal sabzi, fluffy rice, two rotis, pickle & a little sweet.',
        category: 'Kitchen favourites',
        price: 18900,
        veg: true,
        available: true,
        image: FOOD_IMAGE,
      },
      {
        id: 'm2',
        restaurant_id: 'r1',
        name: 'Paneer butter masala',
        description: 'Soft paneer in a rich tomato gravy. Served with two butter rotis.',
        category: 'Kitchen favourites',
        price: 22900,
        veg: true,
        available: true,
        image: FOOD_IMAGE,
      },
      {
        id: 'm3',
        restaurant_id: 'r1',
        name: 'Chicken rice bowl',
        description: 'Pepper chicken, steamed rice, crunchy onions & house chutney.',
        category: 'Rice & bowls',
        price: 24900,
        veg: false,
        available: true,
        image: FOOD_IMAGE,
      },
      {
        id: 'm4',
        restaurant_id: 'r1',
        name: 'Lemon rice',
        description: 'A bright South Indian classic with peanuts and curry leaves.',
        category: 'Rice & bowls',
        price: 11900,
        veg: true,
        available: true,
        image: FOOD_IMAGE,
      },
      {
        id: 'm5',
        restaurant_id: 'r2',
        name: 'Dum chicken biryani',
        description: 'Fragrant basmati, tender chicken, cooling raita & salan.',
        category: 'Biryani',
        price: 27900,
        veg: false,
        available: true,
        image: FOOD_IMAGE,
      },
      {
        id: 'm6',
        restaurant_id: 'r2',
        name: 'Vegetable dum biryani',
        description: 'Slow-cooked vegetables and basmati with whole spices.',
        category: 'Biryani',
        price: 21900,
        veg: true,
        available: true,
        image: FOOD_IMAGE,
      },
      {
        id: 'm7',
        restaurant_id: 'r3',
        name: 'Roasted paneer bowl',
        description: 'Herbed rice, roasted paneer, greens & mint dressing.',
        category: 'Fresh bowls',
        price: 23900,
        veg: true,
        available: true,
        image: FOOD_IMAGE,
      },
      {
        id: 'm8',
        restaurant_id: 'r3',
        name: 'Chickpea crunch bowl',
        description: 'Spiced chickpeas, cucumber, pickled onion & tahini.',
        category: 'Fresh bowls',
        price: 19900,
        veg: true,
        available: true,
        image: FOOD_IMAGE,
      },
    ],
    riders: [
      {
        id: 'rider-demo',
        name: 'Sam',
        phone: '9876543211',
        vehicle: 'Bike',
        online: true,
        approved: true,
        lat: 12.973,
        lng: 77.6,
        location_updated_at: new Date().toISOString(),
      },
    ],
    orders: [],
  };
}
